<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1620324650328' stop='1620324710371'>
    <name>Test login functionality</name>
    <title>Test login functionality</title>
    <test-cases>
        <test-case start='1620324650328' status='broken' stop='1620324710369'>
            <name>should login with valid credentials</name>
            <title>should login with valid credentials</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-90.0.4430.93'/>
            </parameters>
            <steps>
                <step start='1620324650332' status='broken' stop='1620324710368'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='6f4ddc98-ca33-4608-b44c-a12b6c4ff666-attachment.json' type='application/json' size='48'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "Test login functionality should login with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/vivek/Regenera/test/specs/example.e2e.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "Test login functionality should login with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/vivek/Regenera/test/specs/example.e2e.js)
                    at createTimeoutError (/home/vivek/Regenera/node_modules/mocha/lib/errors.js:491:15)
                    at Test.Runnable._timeoutError (/home/vivek/Regenera/node_modules/mocha/lib/runnable.js:431:10)
                    at Timeout.&lt;anonymous> (/home/vivek/Regenera/node_modules/mocha/lib/runnable.js:246:24)
                    at listOnTimeout (internal/timers.js:554:17)
                    at processTimers (internal/timers.js:497:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>